### ISSUE TITLE
flink-demo-udf.jar 格式损坏

### ISSUE THREAD

**Issue by liucy126** [leonardBang/flink-sql-etl#4]
大咖，能否可以重新上传一个flink-demo-udf.jar，已有的flink-demo-udf.jar格式损坏了。
jar -vtf flink-demo-udf.jar 
java.util.zip.ZipException: error in opening zip file
	at java.util.zip.ZipFile.open(Native Method)
	at java.util.zip.ZipFile.<init>(ZipFile.java:225)
	at java.util.zip.ZipFile.<init>(ZipFile.java:155)
	at java.util.zip.ZipFile.<init>(ZipFile.java:126)
	at sun.tools.jar.Main.list(Main.java:1115)
	at sun.tools.jar.Main.run(Main.java:293)
	at sun.tools.jar.Main.main(Main.java:1288)

**Comment by leonardBang** [comment]
就一个udf函数，工程里有这个目录，maven直接打包一下就好了
